### ISSUE TITLE
Bugs in left sidebar 侧边工具栏功能的bug

### ISSUE THREAD

**Issue by yangjianan666** [documentnode/issues#1]
**Problems of hiding/showing left toolbar**
**左边工具栏(view - left toolbar)[显示/隐藏]功能有问题**

When checking menu item 'View' -> 'Left Toolbar', the left toolbar disappears
勾选view下的left toolbar功能钮,左侧的工具栏却消失了

**Steps to reproduce**
1. Start software, create a new document new01
2. Click 'View' -> 'Left Toolbar', watch the left toolbar
3. Click 'View' -> 'Left Toolbar' again, watch difference of the left toolbar
4. The result is a bug between 'Checking status' and 'Actual left toolbar effect'

**复现步骤**
1. 启动软件,新建一个文档new01
2. 点击上方功能区view - left toolbar,并观察左侧的工具栏变化
3. 再次点击view - left toolbar,观察变化
4. 结果出现`勾选状态`和`实际展示效果`相反的bug

**Expected Result**
By default, the application shows the left toolbar should match the menu item state

**期望结果**
软件默认是显示左侧工具栏的,所以,view下的`left toolbar`

**screenshot**
![image](https://user-images.githubusercontent.com/42053215/55404309-31270780-558a-11e9-93c6-78608e3793e5.png)

**Desktop (please complete the following information):**
 - System: Window 10 Home edition (系统:win10家庭中文版)
 - OS Version: 17134.648 ( 操作系统版本17134.648 )
 - Software Version: Document Node 1.1.86-x64.msi (Windows 64-bit) 测试软件版本为:   Document Node-1.1.86-x64.msi (Windows 64-bit)

**Additional context**
Right Toolbar has a similar issue. 右侧工具栏和right toolbar功能按钮勾选状态一样有此问题.

**Comment by jiakuan** [comment]
@yangjianan666 Thanks for reporting this issue! Will fix it soon.

**Comment by jiakuan** [comment]
Fixed. Will be available in 1.1.87+
