### ISSUE TITLE
first wave problem. ; )

### ISSUE THREAD

**Issue by topcss** [documentnode/issues#11]
1. when the document title too long.
    1. title display is incomplete.
    1. title bar does not have a close bottom.
1. when the project list more than one screen, open a new project does not respond.
1. when too many documents. (e.g: more than 500.)
    1. new document will be very slow.
    1. open the document is also very slow.
1. View -> Editor Only (Meta+Ctrl+E), What is Meta?
1. File -> Recent Files -> Clear Menu, Chear Menu?
1. the program starts is very slowly.
1. There are many identical file names in the same project, **an exception is displayed after the darft is marked.**
1. when a document name appears html tag. (e.g: <>)
    1. the editor title is abnormal.
    1. the document does not exist on the disk, but it was opened. 
1. selecting a folder to copy and paste **will cause the loop create multiple folders.**

**Comment by jiakuan** [comment]
1. Fixed
4. Fixed
8. Fixed
9. Fixed
