### ISSUE TITLE
Suggestion: allow to change font size of UI (建议: 增加一个设置软件字体大小的功能)

### ISSUE THREAD

**Issue by jiahe007** [documentnode/issues#2]
> Please see the screenshot, the default font size on Windows is a bit small. Can you have a setting where we can change the font size?
> 如截图所描述,软件默认的字体稍微有点小,是否可以增加一个设置字体大小的功能?

![image](https://user-images.githubusercontent.com/42053215/55406685-2ae75a00-558f-11e9-8c7f-b56b32595afb.png)

**Comment by jiakuan** [comment]
In the 'Preferences...' dialog, we can change the font size of text editor already. Good suggestion for other font size settings and will think about it.
在“偏好设置”对话框里面，我们已经可以修改文本编辑器里面的字体大小。对于其他字体设置的建议非常好。需要仔细考虑一下。
