### ISSUE TITLE
Suggestion: Change line break from [multiple spaces + Enter] to [direct enter] 建议: 将换行方法由[多空格+enter]修改为[直接enter换行]

### ISSUE THREAD

**Issue by jiahe007** [documentnode/issues#3]
> This is a usibility suggestion:
> 这是一个易用性的建议:

![image](https://user-images.githubusercontent.com/42053215/55408305-54ee4b80-5592-11e9-87cf-1a619966cfc2.png)

**Comment by jiakuan** [comment]
This may be related to the Markdown syntax, where a blank line indicates a paragraph separator. Will do more tests and see if we can improve it.
这可能和Markdown的语法有关。一个空白行表示一个段落分隔符。需要做更多的测试然后看我们能否改进它。

**Comment by yangjianan666** [comment]
@jiakuan 我是用｀简书网｀写文章的时候，发现他们的markdown编辑器是直接enter换行的，好像其他版本markdown都是｀多空格＋回车｀才可以换行的
