### ISSUE TITLE
偏好`preference`_语言`language`、主题样式`theme`_无法修改

### ISSUE THREAD

**Issue by jiahe007** [documentnode/issues#4]
**Describe the bug**
软件的偏好设置`preference`_语言`language`、主题样式`theme`_存在问题，无法即时完成修改

**To Reproduce**
1. 点击`file`，点击`preference`
2. 点击`general_theme`的选项,改为`light`
3. 点击 `general_language`的选项，改为`简体中文`
4. 点击`apply`(or OK)
5. **error**：1）软件的**主题样式修改没有立即生效**，仍然保持默认的darcula样式；2）软件的**语言没有立刻变为简体中文**，仍然是American English【截图一】
6. 退出并重启软件，观察主题样式和语言，发现**error**：主题样式变为light，但是，功能设置窗口内的文字显示不清楚【截图二】

**Expected behavior**
- 点击应用apply按钮，修改可以立即生效
- 优化light主题下的文字显示效果

**Screenshots**

截图一
![截图一](https://user-images.githubusercontent.com/42053215/55619937-49866480-57cc-11e9-99b6-66d311e9c0e2.png)

截图二
![截图二](https://user-images.githubusercontent.com/42053215/55621557-6f156d00-57d0-11e9-9f49-210c9b07d4c4.png)

**Desktop (please complete the following information):**
- HUAWEI mate d(2018)笔记本电脑
- 系统:win10家庭中文版  
 - 操作系统版本17134.648   
- 测试软件版本为:  Node-1.1.86-x64.msi (Windows 64-bit)

**Comment by jiakuan** [comment]
The issue of switching themes has been fixed in 1.1.87:
https://www.kickstarter.com/projects/jakew/document-node-fast-native-all-in-one-writing-tool/posts/2470998

The language switching will be handled in future versions.

I will send you the new version for tests soon. Thanks.

**Comment by jiahe007** [comment]
已经新增了多国语言，并且主题样式切换也已经修改为直接变化。
