### ISSUE TITLE
编辑区的高亮效果显示有问题_缺少规律性

### ISSUE THREAD

**Issue by jiahe007** [documentnode/issues#5]
**Describe the bug**
编辑器-编辑区内的代码行显示的效果有问题，显示的没有规律，不方便用户使用（look at the screenshot）

**To Reproduce**
1. 进入编辑器_编辑区，输入下面这段文字
>目的是`考察客户端应用的性能`，测试的入口是客户端。主要包括`并发性能测试`、`疲劳强度测试`、`大数据量测试`和`速度测试`等。   **`并发性能测试是重点`** 
2. **error**：查看文本显示的样式，``号内的**代码行**文字没有统一成一种颜色【看截图】

**Expected behavior**
编辑器_编辑区内的文字高亮，应该有明确的规律，比如，代码行``内的文字显示不同颜色，代码行外的文字显示默认颜色。

**Screenshots**
bug截图（附文字描述）
![image](https://user-images.githubusercontent.com/42053215/55622729-96ba0480-57d3-11e9-84f6-dfceebb7d017.png)

**Desktop (please complete the following information):**
- 系统:win10家庭中文版   
- 操作系统版本17134.648   
- 测试软件版本为:  Node-1.1.86-x64.msi (Windows 64-bit)

**Comment by jiakuan** [comment]
Good finding! Syntax highlighting for Chinese characters does have issues. Will check and fix.

**Comment by jiakuan** [comment]
@jiahe007 This one has been fixed and will be available in 1.1.91+ for tests.

**Comment by jiahe007** [comment]
编辑区内，高亮显示已经规范了
