### ISSUE TITLE
On Windows, 'Delete' key should remove characters after text cursor

### ISSUE THREAD

**Issue by jiakuan** [documentnode/issues#7]
**Describe the bug**
Unlike Mac keyboard, on most Windows keyboards, there are two separate keys: `Delete` and `Backspace`. The normal behaviour should be:

* `Backspace` key should remove characters before the text cursor
* `Delete` key should remove characters after the text cursor

**To Reproduce**
1. Launch Document Node on a Windows machine
2. Open a Markdown document in the text editor
3. Put the text cursor between characters
4. Press `Delete` key and `Backspace`

**Expected behavior**

* `Backspace` key should remove characters before the text cursor
* `Delete` key should remove characters after the text cursor

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: N/A
 - Version: 1.1.87

**Additional context**
N/A

**Comment by jiakuan** [comment]
@yangjianan666 This one has been fixed, please test again in 1.1.90+, Thanks.

**Comment by jiahe007** [comment]
功能已正常,Windows系统下验证无误.
