### ISSUE TITLE
启动软件，如果默认打开了文档，但没打开项目，那么新建Document会出现无法选择保存目录的bug

### ISSUE THREAD

**Issue by jiahe007** [documentnode/issues#9]
**Describe the bug**
启动软件时，如果是打开文档但没有打开项目的情况下，新建document时，无法选择保存的目录。

**To Reproduce**
1. 启动软件，此时发现之前打开的文档是打开的状态，但是没有看见打开项目
2. 此时新建一个document，输入文件名
3. 点击选择要保存的目录位置
4. See error：点击无反应，不能打开选择保存目录的窗口

**Expected behavior**
期望：
1. 启动软件后，默认打开之前编辑的文档和项目，新建Document时，默认保存在之前的项目目录下面
2. 每次启动软件，总是打开上次编辑的项目和文档，不能只打开文档却不关联项目目录
**Screenshots**
![image](https://user-images.githubusercontent.com/42053215/56203298-862d4800-6077-11e9-8564-04a0bccdd23b.png)

**Desktop (please complete the following information):**
 - Windows10家庭版

**Comment by jiakuan** [comment]
Just fixed this one. It will be available in 1.1.91+

**Comment by jiahe007** [comment]
经过验证，已经修复了bug
